// 16-byte packet -> 64-byte packet
#define KVM_USB_OUT_REPORT_ID 0x10U
#define KVM_USB_OUT_REPORT_SIZE 64U
#define KVM_USB_OUT_HEADER_SIZE 5U
#define KVM_USB_OUT_PAYLOAD_SIZE 59U

#define KVM_PROTOCOL_VERSION 0x01U

#define KVM_TYPE_KEYBOARD 0x01U
#define KVM_TYPE_MOUSE 0x02U
#define KVM_TYPE_RELEASE_ALL 0x03U
#define KVM_TYPE_PING 0x04U