// 16-byte packet -> 64-byte packet
#define KVM_USB_OUT_REPORT_ID 0x10U
#define KVM_USB_OUT_REPORT_SIZE 64U
#define KVM_USB_OUT_HEADER_SIZE 5U
#define KVM_USB_OUT_PAYLOAD_SIZE 59U

#define KVM_PROTOCOL_VERSION 0x01U

#define KVM_TYPE_KEYBOARD 0x01U
#define KVM_TYPE_MOUSE 0x02U
#define KVM_TYPE_RELEASE_ALL 0x03U
#define KVM_TYPE_PING 0x04U

#define KVM_TYPE_STATUS 0x80U

#define KVM_STATUS_OK 0x00U
#define KVM_STATUS_BAD_LENGTH 0x01U
#define KVM_STATUS_UNKNOWN_TYPE 0x02U
#define KVM_STATUS_TARGET_SEND_FAIL 0x03U